project:
  type: book

book:
  title: "群论在物理学中的应用"
  author: "申志涛"

  chapters:
    - index.qmd
    - chapters/01-introduction.qmd
    - chapters/02-group.qmd

format:
  html:
    toc: true
    number-sections: true



